# Installer configuration file
# Specify the source directory and the target destinations for skill synchronization

source: "./skills"

targets:
  - "~/.gemini/antigravity/skills/"
  - "~/.config/opencode/skills/"
  - "./.cursor/rules/"
  - "./.github/skills/"

prompts:
  source: "IDE-AGENT.md"
  targets:
    - "~/.gemini/GEMINI.md"
    - "~/.config/opencode/AGENTS.md"
    - "./.windsurfrules"
    - "./.github/copilot-instructions.md"
